### ISSUE TITLE
简化、优化变量

### ISSUE THREAD

**Issue by nervouna** [jysperm/leancloud-budget#1]
现在计算用的变量包括：

1. 总用户数
2. 活跃用户占比
3. 用户日均活跃时间
4. 活跃状态的 QPM
5. 平均请求处理时间
6. 用户活跃时间段

准备改为：

1. 每日活跃用户（`dailyActiveUser`）
2. 用户平均每日打开次数（`sessionsPerUserPerDay`）
3. 用户单次打开请求数量（`requestsPerSession`）
4. 用户活跃时间段（`dailyActiveHours`）

计算方法：

```jsx
// LeanCloud 的承诺响应时间
const responseTime = 15 

// 每日请求量
const requestsPerDay = dailyActiveUser * sessionsPerDay * requestsPerSession
// QPS
const qps = requestsPerDay / ( dailyActiveHours * 3600 )
// 工作线程
const worker = qps / ( 1000 / responseTime )
```

更改指标的原因是，相对原来的指标，日活、用户打开次数、用户每次打开请求数这些指标，对用户来讲比较好预估。

另外根据今天讨论，我们似乎是可以通过一个测试 demo 给用户一个响应时间的预期值的？据陈伟的说法看来这个值是 15～25 毫秒？如果是的话那么这个值可以当作一个常量。

@jysperm 你觉得靠谱么

**Comment by jysperm** [comment]
我们白天的讨论提到突出并发的重要原因就是希望用户意识到不同类型的请求有着不同的处理时间，所以我觉得不应该把 responseTime 作为一个常量，而是要让用户知道这是其中一个影响因子，在滚动条的取值上面，我觉得可以改为几档（而不是现在从 10 到 1000）：20ms、50ms、100ms，然后在每个档位上面加一些注释。

改成「用户平均每日打开次数」和「用户单次打开请求数量」我觉得很好，另外不知道这些指标在我们的统计模块里是否有展示？我们可以参考一下大多数应用的这些指标是怎样的。

**Comment by nervouna** [comment]
> 我觉得可以改为几档（而不是现在从 10 到 1000）：20ms、50ms、100ms，然后在每个档位上面加一些注释。

好，具体应该设为几档，以及每个档位对应的请求类型是什么，能拜托你出一个吗

> 改成「用户平均每日打开次数」和「用户单次打开请求数量」我觉得很好，另外不知道这些指标在我们的统计模块里是否有展示？我们可以参考一下大多数应用的这些指标是怎样的。

这个去看统计意义上的总体数据其实意义不大，因为根据业务类型不同，这些数据可能天差地别。我去看看有没有现成的统计数据可参考吧。

**Comment by jysperm** [comment]
已按照这个 Issue 中的描述修改，你可能需要按住 shift 刷新来看效果
